config/routes.rb
Rails.application.routes.draw do
  root 'exams#index'
  get '/exams' => 'exams#index'
  get '/exams/new' => 'exams#new'
  post '/exams/create_exam' => 'exams#create_exam'
  delete '/exams/:exam_id/delete_exam' => 'exams#delete_exam', as: :delete_exam
  get '/exams/:exam_id/show_exam' => 'exams#show_exam', as: :show_exam
  get '/questions' => 'questions#index'
  get '/exams/:exam_id/questions/new' => 'questions#new', as: :new_question
  post '/exams/:exam_id/questions/create_question' => 'questions#create_question', as: :create_question
  get '/exams/:exam_id/questions' => 'student_answers#exam_questions', as: :exam_question
  get '/exams/:exam_id/questions/:question_id/student_answers/new' => 'student_answers#new', as: :new_student_answer
  post '/exams/:exam_id/questions/student_answers/create_answer' => 'student_answers#create_answer', as: :create_student_answer
  get '/user/index' => 'user#index'
  get '/user/:user_id/view_result' => 'user#view_result', as: :view_result

    devise_for :users, :controllers => {registrations: 'registrations'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :exam
  has_many :student_answers
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index
		@questions = Question.all
	end

	def new
	end

	def create_question
		Question.create(question: params[:question], first_option: params[:first_option], second_option: params[:second_option], third_option: params[:third_option], fourth_option: params[:fourth_option], correct_option: params[:correct_option], exam_id: params[:exam_id])
	end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/create_question.html.erb
<h2>Question created successfully.</h2>

app/views/questions/index.html.erb
<style>
table, th, td {
  border: 1px solid black;
}

table {
  width: 100%;
}
</style>

<table>
  <tr>
    <th>Question List</th>
  </tr>
  <%@questions.each do |question|%>
  <tr>
    <td><%=question.question%></td>
  </tr>
  <%end%>
</table>

app/views/questions/new.html.erb

<h2>Add Question</h2>

<%= form_tag  create_question_path, method: :post do %>
  <%= label_tag "Question:" %>
  <%= text_field_tag :question %><br><br>
  <%= label_tag "First Option:" %>
  <%= text_field_tag :first_option %><br><br>
  <%= label_tag "Second Option:" %>
  <%= text_field_tag :second_option %><br><br>
  <%= label_tag "Third Option:" %>
  <%= text_field_tag :third_option %><br><br>
  <%= label_tag "Fourth Option:" %>
  <%= text_field_tag :fourth_option %><br><br>
  <%= label_tag "Correct Option:" %>
  <%= text_field_tag :correct_option %><br><br>

   <%= submit_tag("Save") %>
<%end%>
