config/routes.rb
Rails.application.routes.draw do
  root 'exams#index'
  get '/exams' => 'exams#index'
  get '/exams/new' => 'exams#new'
  post '/exams/create_exam' => 'exams#create_exam'
  delete '/exams/:exam_id/delete_exam' => 'exams#delete_exam', as: :delete_exam
  get '/exams/:exam_id/show_exam' => 'exams#show_exam', as: :show_exam
  get '/questions' => 'questions#index'
  get '/exams/:exam_id/questions/new' => 'questions#new', as: :new_question
  post '/exams/:exam_id/questions/create_question' => 'questions#create_question', as: :create_question
  get '/exams/:exam_id/questions' => 'student_answers#exam_questions', as: :exam_question
  get '/exams/:exam_id/questions/:question_id/student_answers/new' => 'student_answers#new', as: :new_student_answer
  post '/exams/:exam_id/questions/student_answers/create_answer' => 'student_answers#create_answer', as: :create_student_answer
  get '/user/index' => 'user#index'
  get '/user/:user_id/view_result' => 'user#view_result', as: :view_result

    devise_for :users, :controllers => {registrations: 'registrations'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/exam.rb
class Exam < ApplicationRecord
	has_many :questions, dependent: :delete_all
	has_many :student_answers

	def total_score
		self.questions.count
	end

	def marks(user_id)
		marks = 0
		self.questions.each do |question|
			if StudentAnswer.where(user_id: user_id, question_id: question.id).present? && question.correct_option == StudentAnswer.where(user_id: user_id, question_id: question.id).first.try(:answer)
				marks += 1
			else
				marks += 0
			end
		end
		marks
	end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
    skip_before_action :verify_authenticity_token

	def index
		@exams = Exam.all
	end

	def new
	end

	def create_exam
		Exam.create(question_paper: params[:question_paper])
		puts params
	end

	def delete_exam
		exam_id = params[:exam_id]
		@exams = Exam.find(exam_id)
		@exams.destroy
	end

	def show_exam
		@questions = Exam.find(params[:exam_id]).questions.all
	end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/create_exam.html.erb
<h2>Exam created successfully</h2>

app/views/exams/delete_exam.html.erb
<h2>Exam deleted successfully.</h2>

app/views/exams/index.html.erb
<h2>This is my Registration app.</h2>

<%= link_to "Log out", destroy_user_session_path, :method => :delete %>
<%= link_to "Student Scoreboard", user_index_path %>

<% if current_user.role == "teacher" %>
  <%= link_to "Create Exam", exams_new_path, :method => :get %>
<%end%>

<% if current_user.role == "teacher" %>

<style>
table, th, td {
  border: 1px solid black;
}

table {
  width: 100%;
}
</style>
<h2>List of Exams</h2>

<table>
  <tr>
    <th>Question Paper</th>
  </tr>
  <%@exams.each do |exam|%>
  <tr>
    <td><%=exam.question_paper%></td>
    <td><%= link_to "Add Question", new_question_path(exam_id: exam.id) %></td>
    <td><%= link_to "Delete Exam", delete_exam_path(exam_id: exam.id), :method => :delete %></td>
    <td><%= link_to "Show Exam", show_exam_path(exam_id: exam.id) %></td>
  </tr>
  <%end%>
</table>

<%else%>

<style>
table, th, td {
  border: 1px solid black;
}

table {
  width: 100%;
}
</style>
<h2>Student Dashboard</h2>

<table>
  <tr>
    <th>Question Papers</th>
  </tr>
    <%@exams.each do |exam|%>
    <tr>
      <td><%=exam.question_paper%></td>
      <td><%= link_to "Take Exam", exam_question_path(exam_id: exam.id) %></td>
    </tr>
    <%end%>
</table>

<%end%>


app/views/exams/new.html.erb
<h2>Create Exam</h2>

<%= form_tag exams_create_exam_path, method: :post do %>
  <%= label_tag "Question Paper:" %>
  <%= text_field_tag :question_paper %><br><br>

  <%= submit_tag("Create Exam") %>
<%end%>

app/views/exams/show_exam.html.erb
<style>
table, th, td {
  border: 1px solid black;
}

table {
  width: 100%;
}
</style>
<h2>Exam</h2>

<table>
  <tr>
    <th>Question</th>
    <th>first_option</th>
    <th>Second_option</th>
    <th>Third_option</th>
    <th>Fourth_option</th>
    <th>Correct_option</th>
  </tr>
  <%@questions.each do |question|%>
  <tr>
    <td><%=question.question%></td>
    <td><%=question.first_option%></td>
    <td><%=question.second_option%></td>
    <td><%=question.third_option%></td>
    <td><%=question.fourth_option%></td>
    <td><%=question.correct_option%></td>
  </tr>
  <%end%>
</table>