config/routes.rb
Rails.application.routes.draw do
  root 'exams#index'
  get '/exams' => 'exams#index'
  get '/exams/new' => 'exams#new'
  post '/exams/create_exam' => 'exams#create_exam'
  delete '/exams/:exam_id/delete_exam' => 'exams#delete_exam', as: :delete_exam
  get '/exams/:exam_id/show_exam' => 'exams#show_exam', as: :show_exam
  get '/questions' => 'questions#index'
  get '/exams/:exam_id/questions/new' => 'questions#new', as: :new_question
  post '/exams/:exam_id/questions/create_question' => 'questions#create_question', as: :create_question
  get '/exams/:exam_id/questions' => 'student_answers#exam_questions', as: :exam_question
  get '/exams/:exam_id/questions/:question_id/student_answers/new' => 'student_answers#new', as: :new_student_answer
  post '/exams/:exam_id/questions/student_answers/create_answer' => 'student_answers#create_answer', as: :create_student_answer
  get '/user/index' => 'user#index'
  get '/user/:user_id/view_result' => 'user#view_result', as: :view_result

    devise_for :users, :controllers => {registrations: 'registrations'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student_answer.rb
class StudentAnswer < ApplicationRecord
  belongs_to :exam
  belongs_to :question
  belongs_to :user
end

app/controllers/student_answers_controller.rb
class StudentAnswersController < ApplicationController

	def exam_questions
		@exam = Exam.find(params[:exam_id])
		@questions = @exam.questions
	end

	def new
		@exam_id = params[:exam_id]
		@question_id = params[:question_id] 
		@user_id = params[:user_id]
	end

	def create_answer
		StudentAnswer.create(answer: params[:answer], exam_id: params[:exam_id], question_id: params[:question_id], user_id: current_user.id)
		puts params
	end
end

app/helpers/student_answers_helper.rb
module StudentAnswersHelper
end

app/views/student_answers/create_answer.html.erb
<h3>Answer submitted successfully.</h3>

app/views/student_answers/exam_questions.html.erb
<style>
table, th, td {
  border: 1px solid black;
}

table {
  width: 100%;
}
</style>
<h2>Take Exam</h2>

<table>
  <tr>
    <th>Question</th>
    <th>first_option</th>
    <th>Second_option</th>
    <th>Third_option</th>
    <th>Fourth_option</th>
    <th>Answer Here</th>
  </tr>
  <%@questions.each do |question|%>
  <tr>
    <td><%=question.question%></td>
    <td><%=question.first_option%></td>
    <td><%=question.second_option%></td>
    <td><%=question.third_option%></td>
    <td><%=question.fourth_option%></td>
    <% if StudentAnswer.where(exam_id: @exam.id, user_id: current_user.id, question_id: question.id).present? %>
    <td>Submitted</td>
    <%else%>
    <td><%= link_to "Click here to Submit Answer", new_student_answer_path(exam_id: @exam.id, question_id: question.id, user_id: current_user.id) %></td>
    <%end%>
  </tr>
  <%end%>
</table>

      

app/views/student_answers/new.html.erb
<h3>Submit Answer</h3>

<%= form_tag create_student_answer_path, method: :post do %>
  <%= label_tag "Answer:" %>
  <%= text_field_tag :answer %><br><br>
  <%= hidden_field_tag(:exam_id, @exam_id) %>
  <%= hidden_field_tag(:question_id, @question_id) %>
  <%= hidden_field_tag(:user_id, @user_id) %>

   <%= submit_tag("Submit Answer") %>
<%end%>